### ISSUE TITLE
Electron not found

### ISSUE THREAD

**Issue by mar1n3r0** [stanfieldr/ghetto-skype#103]
Hi,

I am building ghetto-skype on Void Linux. The structure does seems different after building because the package.json is located in /opt/ghetto-skype/resources/app/ rather than /opt/ghetto-skype.

When I run npm --prefix /opt/ghetto-skype/resources/app/ start I get electron not found. 

Here is the npm log:

0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/ghetto-skype/resources/app/',
1 verbose cli   'start' ]
2 info using npm@3.10.8
3 info using node@v6.9.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ghetto-skype@1.4.1~prestart: ghetto-skype@1.4.1
6 silly lifecycle ghetto-skype@1.4.1~prestart: no script for prestart, continuing
7 info lifecycle ghetto-skype@1.4.1~start: ghetto-skype@1.4.1
8 verbose lifecycle ghetto-skype@1.4.1~start: unsafe-perm in lifecycle true
9 verbose lifecycle ghetto-skype@1.4.1~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/opt/ghetto-skype/resources/app/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin:/sbin:/bin
10 verbose lifecycle ghetto-skype@1.4.1~start: CWD: /opt/ghetto-skype/resources/app
11 silly lifecycle ghetto-skype@1.4.1~start: Args: [ '-c', 'electron .' ]
12 info lifecycle ghetto-skype@1.4.1~start: Failed to exec start script
13 verbose stack Error: ghetto-skype@1.4.1 start: `electron .`
13 verbose stack spawn ENOENT
13 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:33:16)
13 verbose stack     at emitTwo (events.js:106:13)
13 verbose stack     at ChildProcess.emit (events.js:191:7)
13 verbose stack     at maybeClose (internal/child_process.js:877:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
14 verbose pkgid ghetto-skype@1.4.1
15 verbose cwd /opt/ghetto-skype/resources/app
16 error Linux 4.8.6_1
17 error argv "/usr/bin/node" "/usr/bin/npm" "--prefix" "/opt/ghetto-skype/resources/app/" "start"
18 error node v6.9.1
19 error npm  v3.10.8
20 error file sh
21 error code ELIFECYCLE
22 error errno ENOENT
23 error syscall spawn
24 error ghetto-skype@1.4.1 start: `electron .`
24 error spawn ENOENT
25 error Failed at the ghetto-skype@1.4.1 start script 'electron .'.
25 error Make sure you have the latest version of node.js and npm installed.
25 error If you do, this is most likely a problem with the ghetto-skype package,
25 error not with npm itself.
25 error Tell the author that this fails on your system:
25 error     electron .
25 error You can get information on how to open an issue for this project with:
25 error     npm bugs ghetto-skype
25 error Or if that isn't available, you can get their info via:
25 error     npm owner ls ghetto-skype
25 error There is likely additional logging output above.
26 verbose exit [ 1, true ]

What could it be ? 

P.S. I can test run it without a problem. And yes, this is a great neat alternative to the official client.

Thank you.

**Comment by code-hunger** [comment]
Have you installed electron? From the error log it seems it's just not installed. Install it and then try again.

**Comment by mar1n3r0** [comment]
Thanks for replying and sorry for the delayed response. I don't have electron as a package on my distro(Void Linux). Probably that's the issue. Although it seemed self-contained in the ghetto-skype package itself ?

**Comment by code-hunger** [comment]
On my arch linux electron is a dependency of ghetto-skype. As I see there's no package `electron` in Void Linux so you'll have to install it manually. Look at the official https://github.com/electron/electron page for how to install it.
