### ISSUE TITLE
Questions about new Build System

### ISSUE THREAD

**Issue by nlowe** [stanfieldr/ghetto-skype#115]
Hey @stanfieldr,

I'm working on getting 1.5.0 packaged for arch and am running into some issues. First, you need to run `npm install` before trying to run `npm run dist`. I think you may want to make that more clear in the readme.

Also, it seems that `icns2png` is from `libicns`, which I had to install to get past the first issue with the build instructions. Not sure if other distros include this by default or with other dependencies, but something you may want to add to the readme.

Now, it appears that something is failing with the build. I've used `fpm` before, but not `electron-builder`, so I'm not sure if I'm missing dependencies or if the build script doesn't like my shell. Here's what happens when I run `npm run dist`:

```fish
nathan@nathan-arch ~/p/ghetto-skype ((v1.5.0))> npm run dist                                                                                 20:13:14

> ghetto-skype@ dist /home/nathan/projects/ghetto-skype
> build

Rebuilding native production dependencies for linux:x64
Packaging for linux x64 using electron 1.4.13 to dist/linux-unpacked
Building pacman
Error: Exit code: 1. Command failed: /home/nathan/.cache/electron-builder/fpm/fpm-1.6.3-2.3.1/fpm -s dir -t pacman --architecture amd64 --name ghetto-skype --force --after-install /tmp/electron-builder-lc6d9F/0-3-after-install --after-remove /tmp/electron-builder-lc6d9F/0-4-after-remove --description 
 Integrates Web Skype with the Linux desktop --maintainer Nathan Lowe <techwiz96@gmail.com> --vendor Robert Stanfield <robert@stanfield.it> --version 1.5.0 --package /home/nathan/p1dd9ad42e94b53149e03f0ff8e06bc771f25a7d0a2e0b856ee8ae347a561225f (sha256 hash) --url https://github.com/stanfieldr/ghetto-skype --license GPL-3.0 /home/nathan/projects/ghetto-skype/dist/linux-unpacked/=/opt/Ghetto Skype /tmp/electron-builder-lc6d9F/0-2-linux.iconset/icon_16x16x32.png=/usr/share/icons/hicolor/16x16/apps/ghetto-skype.png /tmp/electron-builder-lc6d9F/0-2-linux.iconset/icon_24x24x32.png=/usr/share/icons/hicolor/24x24/apps/ghetto-skype.png /tmp/electron-builder-lc6d9F/0-2-linux.iconset/icon_32x32x32.png=/usr/share/icons/hicolor/32x32/apps/ghetto-skype.png /tmp/electron-builder-lc6d9F/0-2-linux.iconset/icon_48x48x32.png=/usr/share/icons/hicolor/48x48/apps/ghetto-skype.png /tmp/electron-builder-lc6d9F/0-2-linux.iconset/icon_64x64x32.png=/usr/share/icons/hicolor/64x64/apps/ghetto-skype.png /tmp/electron-builder-lc6d9F/0-2-linux.iconset/icon_96x96x32.png=/usr/share/icons/hicolor/96x96/apps/ghetto-skype.png /tmp/electron-builder-lc6d9F/0-2-linux.iconset/icon_128x128x32.png=/usr/share/icons/hicolor/128x128/apps/ghetto-skype.png /tmp/electron-builder-lc6d9F/0-2-linux.iconset/icon_256x256x32.png=/usr/share/icons/hicolor/256x256/apps/ghetto-skype.png /tmp/electron-builder-lc6d9F/0-2-linux.iconset/icon_512x512x32.png=/usr/share/icons/hicolor/512x512/apps/ghetto-skype.png /tmp/electron-builder-lc6d9F/0-1-Ghetto Skype.desktop=/usr/share/applications/Ghetto Skype.desktop

{:timestamp=>"2016-12-22T20:13:24.347396-0500", :message=>"Process failed: /usr/bin/fish failed (exit code 127). Full command was:[\"/usr/bin/fish\", \"-c\", \"LANG=C bsdtar -czf .MTREE --format=mtree --options='!all,use-set,type,uid,gid,mode,time,size,md5,sha256,link' .INSTALL .PKGINFO usr opt\"]", :level=>:error}

    at /home/nathan/projects/ghetto-skype/node_modules/electron-builder/src/util/util.ts:77:16
    at ChildProcess.exithandler (child_process.js:218:5)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:885:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
From previous event:
    at exec (/home/nathan/projects/ghetto-skype/node_modules/electron-builder/src/util/util.ts:55:3)
    at /home/nathan/projects/ghetto-skype/node_modules/electron-builder/src/targets/fpm.ts:162:11
    at Generator.next (<anonymous>)
From previous event:
    at FpmTarget.build (/home/nathan/projects/ghetto-skype/node_modules/electron-builder/out/targets/fpm.js:210:11)
    at default.each.it (/home/nathan/projects/ghetto-skype/node_modules/electron-builder/src/platformPackager.ts:171:87)
From previous event:
    at postAsyncTasks.push.default.map.then (/home/nathan/projects/ghetto-skype/node_modules/electron-builder/src/platformPackager.ts:171:35)
From previous event:
    at LinuxPackager.packageInDistributableFormat (/home/nathan/projects/ghetto-skype/node_modules/electron-builder/src/platformPackager.ts:171:8)
    at /home/nathan/projects/ghetto-skype/node_modules/electron-builder/src/platformPackager.ts:166:10
From previous event:
    at LinuxPackager.pack (/home/nathan/projects/ghetto-skype/node_modules/electron-builder/out/platformPackager.js:219:11)
    at /home/nathan/projects/ghetto-skype/node_modules/electron-builder/src/packager.ts:146:22
From previous event:
    at Packager.doBuild (/home/nathan/projects/ghetto-skype/node_modules/electron-builder/out/packager.js:275:11)
    at /home/nathan/projects/ghetto-skype/node_modules/electron-builder/src/packager.ts:114:38
    at Generator.next (<anonymous>)
    at runCallback (timers.js:651:20)
    at tryOnImmediate (timers.js:624:5)
    at processImmediate [as _immediateCallback] (timers.js:596:5)
From previous event:
    at Packager.build (/home/nathan/projects/ghetto-skype/node_modules/electron-builder/out/packager.js:227:11)
    at /home/nathan/projects/ghetto-skype/node_modules/electron-builder/src/builder.ts:241:40
    at Generator.next (<anonymous>)
From previous event:
    at build (/home/nathan/projects/ghetto-skype/node_modules/electron-builder/out/builder.js:89:21)
    at Object.<anonymous> (/home/nathan/projects/ghetto-skype/node_modules/electron-builder/out/cli/build-cli.js:68:41)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.runMain (module.js:605:10)
    at run (bootstrap_node.js:420:7)
    at startup (bootstrap_node.js:139:9)
    at bootstrap_node.js:535:3

npm ERR! Linux 4.8.13-1-ARCH
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "run" "dist"
npm ERR! node v7.3.0
npm ERR! npm  v4.0.5
npm ERR! code ELIFECYCLE
npm ERR! ghetto-skype@ dist: `build`
npm ERR! Exit status 255
npm ERR! 
npm ERR! Failed at the ghetto-skype@ dist script 'build'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the ghetto-skype package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     build
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs ghetto-skype
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls ghetto-skype
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/nathan/projects/ghetto-skype/npm-debug.log
```

Any clues?

**Comment by nlowe** [comment]
Here's the verbose log if that helps:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node', '/usr/bin/npm', 'run', 'dist' ]
2 info using npm@4.0.5
3 info using node@v7.3.0
4 verbose run-script [ 'predist', 'dist', 'postdist' ]
5 info lifecycle ghetto-skype@~predist: ghetto-skype@
6 silly lifecycle ghetto-skype@~predist: no script for predist, continuing
7 info lifecycle ghetto-skype@~dist: ghetto-skype@
8 verbose lifecycle ghetto-skype@~dist: unsafe-perm in lifecycle true
9 verbose lifecycle ghetto-skype@~dist: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/home/nathan/projects/ghetto-skype/node_modules/.bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/opt/android-sdk/platform-tools:/opt/android-sdk/tools:/opt/depot_tools:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
10 verbose lifecycle ghetto-skype@~dist: CWD: /home/nathan/projects/ghetto-skype
11 silly lifecycle ghetto-skype@~dist: Args: [ '-c', 'build' ]
12 silly lifecycle ghetto-skype@~dist: Returned: code: 255  signal: null
13 info lifecycle ghetto-skype@~dist: Failed to exec dist script
14 verbose stack Error: ghetto-skype@ dist: `build`
14 verbose stack Exit status 255
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:279:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:885:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:226:5)
15 verbose pkgid ghetto-skype@
16 verbose cwd /home/nathan/projects/ghetto-skype
17 error Linux 4.8.13-1-ARCH
18 error argv "/usr/bin/node" "/usr/bin/npm" "run" "dist"
19 error node v7.3.0
20 error npm  v4.0.5
21 error code ELIFECYCLE
22 error ghetto-skype@ dist: `build`
22 error Exit status 255
23 error Failed at the ghetto-skype@ dist script 'build'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ghetto-skype package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     build
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ghetto-skype
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ghetto-skype
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by nlowe** [comment]
Hmm, seems to be my shell. `chsh`'ing to `/bin/bash` and logging out and back in seems to have fixed it. Unfortunately creating a sub shell (`/bin/bash -c "npm run dist"`) didn't work, it still wanted to use `/usr/bin/fish`. Looks like an upstream issue w/ `fpm`

**Comment by nlowe** [comment]
Using the `dir` target works. I need to do some different things with the generated package anyways so that ended out working better for me.

I still think some of the readme updates I mentioned should be made. Feel free to close this issue at your leisure.

**Comment by stanfieldr** [comment]
Updated the readme. It may be easier if you skip electron-builder altogether, copy the src dir, then npm install that.
