### ISSUE TITLE
Please build ghetto skype with a more recent version of libjpeg

### ISSUE THREAD

**Issue by pitsi** [stanfieldr/ghetto-skype#148]
Version 1.6.0 fails to start on my debian testing x64 system with this error

```
/opt/Ghetto Skype$ ./ghetto-skype 
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libjpeg.so.8: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:3:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:5:3)

```
Can you please build it with a more recent version of libjpeg instead of that prehistoric libjpeg 8? I call it prehistoric because last time libjpeg 8 was availabe on debian, debian was on version 7, i.e ~5 years ago! If not, please make it a dependency so dpkg will say it can not be installed due to dependency issues and not install it at all.

The issue did not exist in version 1.5.0, which I had to dump in late 2017.
However, I am really thankful that you continue the development of such an app :)

**Comment by coozoo** [comment]
Got the same when tried rpm under fedora
after symlinking libjpeg
got message about that 

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: libgif.so.7: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:3:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:5:3)`

And after symlinking libgif got next

`A JavaScript error occurred in the main process
Uncaught Exception:
Error: /lib/libjpeg.so.8: version `LIBJPEG_8.0' not found (required by /tmp/.org.chromium.Chromium.Bz0KfT)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:3:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:5:3)`

**Comment by stanfieldr** [comment]
@coozoo Are you using the Gnome spin of Fedora? I'm actually running Fedora 27. I installed a vm with blank install of F27 too, but wasn't getting that error. I did notice I uploaded the wrong 64 bit rpm though (built with older version of electron-builder). Does the new rpm work?

**Comment by coozoo** [comment]
@stanfieldr oh 
mine fedora not upgraded yet Fedora release 26 (Twenty Six) with mate desktop
And it is 32 bit so maybe it's only 32 bit issue..

**Comment by ghost** [comment]
Same problem on Debian Sid. The minimum libjpeg version available is libjpeg9.

**Comment by pitsi** [comment]
I noticed earlier that the only "constant" libjpeg version is libjpeg62, so can you please build ghetto skype with this one instead?

**Comment by pitsi** [comment]
I am closing this since ghetto-skype is no longer maintained.
