### ISSUE TITLE
Missing dependency: libpng16

### ISSUE THREAD

**Issue by BitFros7y** [stanfieldr/ghetto-skype#149]
I just downloaded latest release of ghetto-skype i386 package but it just didnt start at all. So i checked processes and it was there. After killing them and restarting nothing happened so i tried to run from terminal.

`ice@Ice-PC ~ $ ghetto-skype
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libpng16.so.16: cannot open shared object file: No such file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:3:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:5:3)`

EDIT: Running `apt install libpng16-16` solved problem (no more errors after that) but its still missing dependence in installation package ( .deb ) and should be fixed.

EDIT 2: Since i renamed issue after fixing.
I use Linux Mint 18.3 (Based on ubuntu 16.04) i386

**Comment by tharrrk** [comment]
reporting that kubuntu 16.04 amd64 has the same issue
I only had libpng12-0 installed
apt install libpng16-16 solved this
