### ISSUE TITLE
Debian stable don't run because want libjpeg.so.8 but libjpeg9, libjpeg62, libjpeg62-turbo, in stable

### ISSUE THREAD

**Issue by PutinVladimir** [stanfieldr/ghetto-skype#151]
Upgrade lib ver and add depends libjpeg62-turbo (preferred) or libjpeg9, libjpeg62 in deb.

~$ ghetto-skype 
Gtk-Message: (for origin information, set GTK_DEBUG): failed to retrieve property `gtk-primary-button-warps-slider' of type `gboolean' from rc file value "((GString*) 0x12fe72a1c860)" of type `gboolean'                                                                                                                                                                                
A JavaScript error occurred in the main process                                                                                                                                              
Uncaught Exception:                                                                                                                                                                          
Error: libjpeg.so.8: cannot open shared object file: No such file or directory                                                                                                               
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)                                                                                                             
    at Object.Module._extensions..node (module.js:598:18)                                                                                                                                    
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)                                                                                                               
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:3:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:5:3)

**Comment by rootbdfy** [comment]
Same problem on debian.
After I try install libjpeg8 from wheezy:
![default](https://user-images.githubusercontent.com/18612349/39196146-14e72a40-47ea-11e8-8e9d-2894644f671b.png)

**Comment by pitsi** [comment]
Please merge this with #148 ...
