### ISSUE TITLE
Bug-report:  ghetto-skype and Xubuntu

### ISSUE THREAD

**Issue by Video-VV** [stanfieldr/ghetto-skype#155]
When I run ghetto-skype, I immediately get an error (I installed the file "ghetto-skype_1.6.0_i386.deb")

```
~$ "/opt/Ghetto Skype/ghetto-skype"
A JavaScript error occurred in the main process
Uncaught Exception:
Error: libgif.so.7: it is impossible to open a shared object 
                                                                                                   file: There is no such 
        file or directory
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:598:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:3:18)
    at Object.<anonymous> (/opt/Ghetto Skype/resources/app.asar/node_modules/canvas/lib/bindings.js:5:3)

```
![image](https://user-images.githubusercontent.com/13081699/44678258-b076ba80-aa40-11e8-869c-480166328a88.png)

About Xubuntu:
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.1 LTS
Release:	18.04
Codename:	bionic

**Comment by winhex** [comment]
Same problem in Ubuntu Mate 18.04 x86

**Comment by winhex** [comment]
1.5 works like a charm in Ubuntu Mate 18.04 x86, so I hope for bugfix release )
