### ISSUE TITLE
NPM Error When Installing

### ISSUE THREAD

**Issue by r-clancy** [stanfieldr/ghetto-skype#77]
When installing, either with the AUR or by doing a git clone and running "npm install", I get the following error:

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/bin/node',
1 verbose cli   '/usr/bin/npm',
1 verbose cli   '--prefix',
1 verbose cli   '/opt/ghetto-skype',
1 verbose cli   'start' ]
2 info using npm@3.10.5
3 info using node@v6.3.1
4 verbose run-script [ 'prestart', 'start', 'poststart' ]
5 info lifecycle ghetto-skype@1.4.0~prestart: ghetto-skype@1.4.0
6 silly lifecycle ghetto-skype@1.4.0~prestart: no script for prestart, continuing
7 info lifecycle ghetto-skype@1.4.0~start: ghetto-skype@1.4.0
8 verbose lifecycle ghetto-skype@1.4.0~start: unsafe-perm in lifecycle true
9 verbose lifecycle ghetto-skype@1.4.0~start: PATH: /usr/lib/node_modules/npm/bin/node-gyp-bin:/opt/ghetto-skype/node_modules/.bin:/usr/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/lib/jvm/default/bin:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
10 verbose lifecycle ghetto-skype@1.4.0~start: CWD: /opt/ghetto-skype
11 silly lifecycle ghetto-skype@1.4.0~start: Args: [ '-c', 'electron .' ]
12 silly lifecycle ghetto-skype@1.4.0~start: Returned: code: 1  signal: null
13 info lifecycle ghetto-skype@1.4.0~start: Failed to exec start script
14 verbose stack Error: ghetto-skype@1.4.0 start: `electron .`
14 verbose stack Exit status 1
14 verbose stack     at EventEmitter.<anonymous> (/usr/lib/node_modules/npm/lib/utils/lifecycle.js:242:16)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at EventEmitter.emit (events.js:191:7)
14 verbose stack     at ChildProcess.<anonymous> (/usr/lib/node_modules/npm/lib/utils/spawn.js:40:14)
14 verbose stack     at emitTwo (events.js:106:13)
14 verbose stack     at ChildProcess.emit (events.js:191:7)
14 verbose stack     at maybeClose (internal/child_process.js:852:16)
14 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:5)
15 verbose pkgid ghetto-skype@1.4.0
16 verbose cwd /home/ryan
17 error Linux 4.6.4-1-ARCH
18 error argv "/usr/bin/node" "/usr/bin/npm" "--prefix" "/opt/ghetto-skype" "start"
19 error node v6.3.1
20 error npm  v3.10.5
21 error code ELIFECYCLE
22 error ghetto-skype@1.4.0 start: `electron .`
22 error Exit status 1
23 error Failed at the ghetto-skype@1.4.0 start script 'electron .'.
23 error Make sure you have the latest version of node.js and npm installed.
23 error If you do, this is most likely a problem with the ghetto-skype package,
23 error not with npm itself.
23 error Tell the author that this fails on your system:
23 error     electron .
23 error You can get information on how to open an issue for this project with:
23 error     npm bugs ghetto-skype
23 error Or if that isn't available, you can get their info via:
23 error     npm owner ls ghetto-skype
23 error There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

I'm trying to install this on my laptop (which runs arch), but it works fine on my desktop (also running arch) - any ideas?

**Comment by stanfieldr** [comment]
Is there a node_modules folder in /opt/ghetto-skype? It might be permissions related. Try cloning it in your home directory and doing an npm install.

**Comment by r-clancy** [comment]
Not sure what has changed, but giving the install another try yields no errors - going to close this issue.
