### ISSUE TITLE
Application won't start

### ISSUE THREAD

**Issue by Vitexus** [stanfieldr/ghetto-skype#82]
Iinstalled form https://github.com/stanfieldr/ghetto-skype/releases/download/v1.4.1/ghetto-skype_1.4.1_amd64.deb on Debian Jessie by command:

sudo gdebi ghetto-skype_1.4.1_amd64.deb

```
vitex@developer:~$ ghetto-skype 
Error { Error: ENOENT: no such file or directory, open '/home/vitex/.config/Ghetto Skype/settings.json'
    at Error (native)
    at Object.fs.openSync (fs.js:640:18)
    at Object.module.(anonymous function) [as openSync] (ELECTRON_ASAR.js:167:20)
    at Object.fs.readFileSync (fs.js:508:33)
    at Object.fs.readFileSync (ELECTRON_ASAR.js:500:29)
    at Object.<anonymous> (/usr/share/ghetto-skype/resources/app/app/GhettoSkype.js:15:34)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
  errno: -2,
  code: 'ENOENT',
  syscall: 'open',
  path: '/home/vitex/.config/Ghetto Skype/settings.json' }
```

**Create The application default empty configuration ?**

**Comment by stanfieldr** [comment]
It actually uses the defaults if the settings file isn't found under ~/.config. I suppressed this particular error and show a more user friendly error now

**Comment by davidak** [comment]
I'm using ghetto-skype for some weeks now and get this error today. 

I use the current version 1.4.1-1.

When the config disapears i consider this a bug.
